# Generated by Django 5.0.6 on 2024-06-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_user_profile_alter_order_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Password',
        ),
        migrations.AddField(
            model_name='employee',
            name='orderd_work',
            field=models.ManyToManyField(blank=True, null=True, to='pages.orderdetail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profile'),
        ),
    ]
