# Generated by Django 5.0.6 on 2024-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_review_fullname_review_email_review_number_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='LevelName',
            field=models.CharField(choices=[('Первый уровень', 'Первый уровень'), ('Второй уровень', 'Второй уровень'), ('Третий уровень', 'Третий уровень'), ('Четвертый уровень', 'Четвертый уровень')], max_length=255),
        ),
    ]
