# Generated by Django 5.0.6 on 2024-06-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_level_levelname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='CreatedAt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='UpdatedAt',
        ),
    ]
