# Generated by Django 5.0.6 on 2024-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_profile_createdat_remove_profile_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='LevelName',
            field=models.CharField(blank=True, choices=[('Первый уровень', 'Первый уровень'), ('Второй уровень', 'Второй уровень'), ('Третий уровень', 'Третий уровень'), ('Четвертый уровень', 'Четвертый уровень')], max_length=255, null=True),
        ),
    ]
