# Generated by Django 5.0.6 on 2024-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_level_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='LevelName',
            field=models.CharField(blank=True, choices=[('Без уровня', 'Без уровня'), ('Первый уровень', 'Первый уровень'), ('Второй уровень', 'Второй уровень'), ('Третий уровень', 'Третий уровень'), ('Четвертый уровень', 'Четвертый уровень')], max_length=255, null=True),
        ),
    ]
