# Generated by Django 5.0.6 on 2024-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_level_levelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='Discount',
            field=models.DecimalField(blank=True, choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20)], decimal_places=2, max_digits=5, null=True),
        ),
    ]
