# Generated by Django 5.0.6 on 2024-06-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_level_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Role',
            field=models.CharField(choices=[('Дизайнер', 'Дизайнер'), ('Пост печатник', 'Пост печатник')], max_length=255),
        ),
    ]
