# Generated by Django 5.0.6 on 2024-06-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='CreatedAt',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='UpdatedAt',
        ),
    ]
