# Generated by Django 5.0.6 on 2024-06-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_employee_createdat_remove_employee_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Принята', 'Принята'), ('В разработке', 'В разработке'), ('Выполнен', 'Выполнен')], default='В обработке', max_length=50),
        ),
    ]
