# Generated by Django 5.0.6 on 2024-06-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
