# Generated by Django 5.0.6 on 2024-06-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_orderdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TotalAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
