# Generated by Django 5.0.6 on 2024-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_order_totalamount_alter_orderdetail_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='Discount',
            field=models.IntegerField(blank=True, choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='TotalAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
